Rewrite the utility to perl
Signed-off-by: Alexey Gladkov <gladkov.alexey@gmail.com>

diff --git a/papt-get.in b/papt-get.in
--- a/papt-get.in
+++ b/papt-get.in
@@ -1,323 +1,334 @@
-#!/bin/bash -efu
-# SPDX-License-Identifier: GPL-2.0-only
+#!/usr/bin/perl
 
-. shell-error
-. shell-temp
-. shell-args
-. shell-signal
-. shell-getopt
+use 5.010;
+use strict;
+use warnings;
 
-export LANG=C
-export LC_ALL=C
+use Text::Wrap;
+use Errno;
+use Fcntl qw/ :flock /;
+use Crypt::Digest qw/ digest_file_hex /;
+use Number::Format qw/ :subs /;
+use AptPkg::Config '$_config';
+use Getopt::Long qw/ :config bundling require_order pass_through /;
 
-show_help()
-{
-	cat <<-EOF
-	Usage: $PROG [options] [install|remove] packages...
-	   or: $PROG [options] dist-upgrade
-	   or: $PROG <apt-get command> [apt-get options]...
+my $apt_dir_archives = '';
+my $apt_dir_downloads = '';
 
-	This utility allows to simultaneously download the packages required for updating the system.
-	This utility is a wrapper for apt-get.
-
-	Options:
-	  -y, --assume-yes      do not ask any questions;
-	  -p, --parallel=N      set the maximum number of parallel downloads;
-	  -v, --verbose         print a message for each action;
-	  -V, --version         print program version and exit;
-	  -h, --help            show this text and exit.
-
-	Report bugs to authors.
-
-	EOF
-	exit
-}
-
-show_version()
-{
-	cat <<-EOF
-	$PROG version @VERSION@
-	Written by Alexey Gladkov, Gleb Fotengauer-Malinovskiy.
-
-	Copyright (C) 2021  Alexey Gladkov <gladkov.alexey@gmail.com>
-	Copyright (C) 2021  Gleb Fotengauer-Malinovskiy <glebfm@altlinux.org>
-
-	This is free software; see the source for copying conditions.  There is NO
-	warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-	EOF
-	exit
-}
-
-get_apt_config()
-{
-	local get_eval get_name get_value
-	get_name="$1"
-	shift || return 1
-	get_value="$1"
-	shift || return 1
-
-	get_eval="$(apt-config shell "$get_value" "$get_name" </dev/null)" || return 1
-	eval "$get_eval"
-}
-
-cols=80
-rows=25
-ttysz()
-{
-	local esc
-	echo -ne "\e[s\e[1000;1000H\e[6n\e[u"
-	IFS=';[' read -s -t2 -dR esc rows cols || {
-		cols=80
-		rows=25
+END {
+	if (defined $apt_dir_downloads && length $apt_dir_downloads && opendir my $dh, $apt_dir_downloads) {
+		while (readdir $dh) {
+			unlink "$apt_dir_downloads/$_";
+		}
+		closedir $dh;
 	}
 }
 
-apt_list()
-{
-	local n
-	n="$1" && shift
-	[ "$#" -eq 0 ] &&
-		eval "apt_list_$n=()" ||
-		eval "apt_list_$n+=(\"\$@\")"
+require 'sys/ioctl.ph';
+
+$0 =~ /^(?:.*\/)?([^\/]+)$/;
+
+my $progname = $1;
+my $verbose = 0;
+my $parallel = 5;
+my $confirmed = 0;
+my $version = 0;
+my $help = 0;
+
+GetOptions(
+	"p=i" => \$parallel,
+	"parallel=i" => \$parallel,
+
+	"v+" => \$verbose,
+	"verbose+"  => \$verbose,
+
+	"y" => \$confirmed,
+	"yes" => \$confirmed,
+	"assume-yes" => \$confirmed,
+
+	"V" => \$version,
+	"version" => \$version,
+
+	"h" => \$help,
+	"help" => \$help,
+) or
+	die "error in command line arguments";
+
+if ($help) {
+	print <<EOF;
+Usage: $progname [options] [install|remove] packages...
+   or: $progname [options] dist-upgrade
+   or: $progname <apt-get command> [apt-get options]...
+EOF
+	print <<'EOF';
+
+This utility allows to simultaneously download the packages required for updating the system.
+This utility is a wrapper for apt-get.
+
+Options:
+  -y, --assume-yes      do not ask any questions;
+  -p, --parallel=N      set the maximum number of parallel downloads;
+  -v, --verbose         print a message for each action;
+  -V, --version         print program version and exit;
+  -h, --help            show this text and exit.
+
+Report bugs to authors.
+
+EOF
+	exit;
 }
 
-apt_list_print()
-{
-	local a
-	declare -n "a=apt_list_$1"
-	shift
-	if [ "${#a[@]}" -gt 0 ]; then
-		printf '%s\n' "$@"
-		printf '%s ' "${a[@]}" | fmt -w $cols | sed -e 's/^/  &/'
-	fi
+if ($version) {
+	print "$progname version ", '@VERSION@', "\n";
+	print <<'EOF';
+Written by Alexey Gladkov, Gleb Fotengauer-Malinovskiy.
+
+Copyright (C) 2021  Alexey Gladkov <gladkov.alexey@gmail.com>
+Copyright (C) 2021  Gleb Fotengauer-Malinovskiy <glebfm@altlinux.org>
+
+This is free software; see the source for copying conditions.  There is NO
+warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
+EOF
+	exit;
 }
 
-apt_status()
-{
-	local n
-	n="$1" && shift
-	[ "$#" -eq 0 ] &&
-		eval "apt_status_$n=0" ||
-		eval "apt_status_$n=\"\$1\""
+die "Opration required" if !@ARGV;
+
+my $command = shift @ARGV;
+
+if ($command =~ /^(install|remove)$/) {
+	die "Package names required" if !@ARGV;
+} elsif ($command =~ /^(dist-upgrade)$/) {
+	;
+} else {
+	exec 'apt-get', $command, @ARGV;
 }
 
-apt_archives=
-exit_handler()
-{
-	[ ! -d "$apt_archives/downloads" ] ||
-		rm -rf -- "$apt_archives/downloads"
+$_config->init();
+$apt_dir_archives = $_config->get("Dir::Cache::archives/d");
+$apt_dir_downloads = "$apt_dir_archives/downloads";
+
+if (! mkdir $apt_dir_downloads) {
+	die "Unable to create downloads directory: $!" unless $!{EEXIST};
 }
 
-GETOPT_ALLOW_UNKNOWN=1
-TEMP=`getopt -n $PROG -o p:,y,h,v,V  -l parallel:,yes,assume-yes,help,verbose,version -- "$@"` ||
-	show_usage
-eval set -- "$TEMP"
+open my $dwn, "<", $apt_dir_downloads or
+	die "Unable to open downloads directory: $!";
 
-confirm=-y
-parallel=5
-apt_args=()
+if (! flock $dwn, LOCK_EX|LOCK_NB) {
+	say "Another process is already using downloads.";
+	exit;
+}
 
-while :; do
-	case "$1" in
-		-p|--parallel)
-			parallel="$(opt_check_number "$1" "$2")"
-			shift
-			;;
-		-y|--yes|--assume-yes)
-			confirm=
-			;;
-		-v|--verbose)
-			verbose=-v
-			;;
-		-h|--help) show_help
-			;;
-		-V|--version) show_version
-			;;
-		--) shift; break
-			;;
-		*)
-			apt_args+=("$(quote_shell "$1")")
-			;;
-	esac
-	shift
-done
+my $winsize = '';
 
-if [ "$#" -eq 0 ]; then
-	message "opration required"
-	show_usage
-fi
+ioctl STDOUT, &TIOCGWINSZ, $winsize or die "ioctl(TIOCGWINSZ): $!";
+my ($rows, $cols, $xpixel, $ypixel) = unpack 'S4', $winsize;
 
-operation="$1"
-shift
+$Text::Wrap::columns = $cols || 72;
 
-case "$operation" in
-	install|remove)
-		if [ "$#" -eq 0 ]; then
-			message "package names required"
-			show_usage
-		fi
-		;;
-	dist-upgrade)
-		;;
-	*)
-		exec apt-get "$operation" "${apt_args[@]}"
-		;;
-esac
+my %info = (
+	'extra-list'     => [],
+	'install-list'   => [],
+	'remove-list'    => [],
+	'upgrade-list'   => [],
+	'downgrade-list' => [],
+	'keep-list'      => [],
+	'hold-list'      => [],
+	'essential-list' => [],
+	'disk-size'      => "0B",
+	'install'        => 0,
+	'remove'         => 0,
+	'upgrade'        => 0,
+	'replace'        => 0,
+	're-install'     => 0,
+	'downgrade'      => 0,
+	'total-size'     => 0,
+	'missing-files'  => [],
+);
 
-get_apt_config Dir::Cache::archives/d apt_archives
-apt_archives="${apt_archives%/}"
+say "Calculating changes...";
 
-[ -d "$apt_archives/downloads" ] ||
-	mkdir -- "$apt_archives/downloads"
+open my $fh, "-|", "apt-get", $command, "-o", "simple-output=yes", "-q=2", "--print-uris", @ARGV or
+	die "Can't start apt-get: $!";
 
-exec 4<"$apt_archives/downloads"
-flock -n 4 ||
-	fatal "another process is already using downloads."
+while (<$fh>) {
+	SWITCH: {
+		if (/^apt-get:((?:extra|install|remove|upgrade|downgrade|keep|hold|essential)-list):(.*)$/) {
+			push @{$info{$1}}, split /\s+/, $2;
+			last SWITCH;
+		}
+		if (/^apt-get:status:(install|remove|upgrade|replace|re-install|downgrade):(\d+)$/) {
+			$info{$1} = $2;
+			last SWITCH;
+		}
+		if (/^apt-get:status:(disk-size):(.*)$/) {
+			$info{$1} = $2;
+			last SWITCH;
+		}
 
-ttysz
+		/^'(?<url>[^']+)' (?<filename>\S+) (?<size>\d+) (?<hash>[A-Fa-f0-9]+)$/;
 
-create_temporary workdir
+		last SWITCH if $+{'url'} =~ /^file:/;
 
-printf "Calculating changes...\n"
-apt-get "$operation" "${apt_args[@]}" -o simple-output=yes -qq --print-uris "$@" > "$workdir/pkgs"
+		push @{$info{'missing-files'}}, {
+				'url' => $+{'url'},
+				'filename' => $+{'filename'},
+				'size' => $+{'size'},
+				'hash' => $+{'hash'}
+		};
 
-for n in extra install remove upgrade downgrade keep hold essential; do
-	apt_list "$n"
-done
+		$info{'total-size'} += $+{'size'};
+	}
+}
+close $fh;
 
-for n in upgrade downgrade install reinstall replace remove disk_size; do
-	apt_status "$n"
-done
+my $everything = 0;
+foreach my $key (qw/ upgrade downgrade install re-install replace remove /) {
+	$everything += $info{$key};
+}
 
-total_size=0
-while read -r s; do
-	case "$s" in
-		apt-get:extra-list:*)        apt_list extra       ${s#apt-get:extra-list:};           continue ;;
-		apt-get:install-list:*)      apt_list install     ${s#apt-get:install-list:};         continue ;;
-		apt-get:remove-list:*)       apt_list remove      ${s#apt-get:remove-list:};          continue ;;
-		apt-get:upgrade-list:*)      apt_list upgrade     ${s#apt-get:upgrade-list:};         continue ;;
-		apt-get:downgrade-list:*)    apt_list downgrade   ${s#apt-get:downgrade-list:};       continue ;;
-		apt-get:keep-list:*)         apt_list keep        ${s#apt-get:keep-list:};            continue ;;
-		apt-get:hold-list:*)         apt_list hold        ${s#apt-get:hold-list:};            continue ;;
-		apt-get:essential-list:*)    apt_list essential   ${s#apt-get:essential-list:};       continue ;;
-		apt-get:status:upgrade:*)    apt_status upgrade   "${s#apt-get:status:upgrade:}";     continue ;;
-		apt-get:status:downgrade:*)  apt_status downgrade "${s#apt-get:status:downgrade:}";   continue ;;
-		apt-get:status:install:*)    apt_status install   "${s#apt-get:status:install:}";     continue ;;
-		apt-get:status:re-install:*) apt_status reinstall "${s#apt-get:status:re-install:}";  continue ;;
-		apt-get:status:replace:*)    apt_status replace   "${s#apt-get:status:replace:}";     continue ;;
-		apt-get:status:remove:*)     apt_status remove    "${s#apt-get:status:remove:}";      continue ;;
-		apt-get:status:disk-size:*)  apt_status disk_size "${s#apt-get:status:disk-size:}";   continue ;;
-	esac
+if ($everything == 0) {
+	say "Nothing to do.";
+	exit;
+}
 
-	csum="${s##* }"; s="${s% *}"
-	size="${s##* }"; s="${s% *}"
-	name="${s##* }"; s="${s% *}"
+my %desc = (
+	'downgrade-list' => "\nThe following packages will be DOWNGRADED:",
+	'essential-list' => "\nWARNING: The following essential packages will be removed\nThis should NOT be done unless you know exactly what you are doing!",
+	'extra-list'     => "\nThe following extra packages will be installed:",
+	'hold-list'      => "\nThe following held packages will be changed:",
+	'install-list'   => "\nThe following NEW packages will be installed:",
+	'keep-list'      => "\nThe following packages have been kept back:",
+	'remove-list'    => "\nThe following packages will be REMOVED:",
+	'upgrade-list'   => "\nThe following packages will be upgraded:",
+);
 
-	url="${s#\'}"; url="${url%\'}"
+foreach my $key (qw/ downgrade-list essential-list extra-list hold-list install-list keep-list remove-list upgrade-list /) {
+	next unless @{$info{$key}};
+	say $desc{$key};
+	say wrap "\t", "\t", join " ", @{$info{$key}};
+}
+say "";
 
-	case "$url" in
-		copy:*)
-			url="file:${url#copy:}"
-			;;
-		file:*)
-			continue
-			;;
-	esac
+my $summary = "Summary";
 
-	algo=md5
-	if [ -z "${csum##*:*}" ]; then
-		algo="${csum%%:*}"
-		algo="${algo,,}"
-		csum="${csum##*:}"
-	fi
+$summary .= ": $info{'upgrade'} upgraded, $info{'install'} newly installed";
+$summary .= ", $info{'re-install'} re-installed" if $info{'re-install'};
+$summary .= ", $info{'downgrade'} downgraded"    if $info{'downgrade'};
+$summary .= ", $info{'replace'} replaced"        if $info{'replace'};
+$summary .= ", $info{'remove'} removed"          if $info{'remove'};
 
-	case "$algo" in
-		md5|md5sum)
-			algo=md5
-			;;
-		sha1|sha256|sha512)
-			;;
-		*)
-			fatal "unknown checksum algorithm: $algo"
-			;;
-	esac
+say $summary;
+say "";
 
-	printf '%s  %s\n' "$csum" "$apt_archives/downloads/$name" >> "$workdir/checksum.$algo"
-	{
-		printf 'url = %q\n' "$url"
-		printf 'output = %q\n' "$apt_archives/downloads/$name"
-	} >> "$workdir/uris"
+say "Need to get ", format_bytes($info{'total-size'}), " of archives.";
+say "After unpacking $info{'disk-size'} of additional disk space will be used.";
 
-	total_size=$(( $total_size + $size ))
-done < "$workdir/pkgs"
+unless ($confirmed) {
+	say "";
 
-nothing=1
-for n in upgrade downgrade install reinstall replace remove; do
-	eval "v=\"\$apt_status_$n\""
-	if [ $v != 0 ]; then
-		nothing=
-		break
-	fi
-done
+	print "Do you want to continue? [Y/n] ";
+	my $answer = <STDIN>;
+	chomp $answer;
 
-if [ -n "$nothing" ]; then
-	printf 'Nothing to do.\n'
-	exit
-fi
+	if (length $answer > 0 and lc $answer ne "y") {
+		say "Abort.";
+		exit;
+	}
+}
 
-apt_list_print upgrade 'The following packages will be upgraded:'
-apt_list_print extra 'The following extra packages will be installed:'
-apt_list_print install 'The following NEW packages will be installed:'
-apt_list_print remove 'The following packages will be REMOVED:'
-apt_list_print keep 'The following packages have been kept back:'
-apt_list_print hold 'The following held packages will be changed:'
-apt_list_print downgrade 'The following packages will be DOWNGRADED:'
-apt_list_print essential \
-	"WARNING: The following essential packages will be removed" \
-	"This should NOT be done unless you know exactly what you are doing!"
+if (@{$info{'missing-files'}}) {
+	say "";
 
-printf '%d upgraded, %d newly installed' "$apt_status_upgrade"  "$apt_status_install"
-[ "$apt_status_reinstall" -eq 0 ] || printf ', %d re-installed' "$apt_status_reinstall"
-[ "$apt_status_downgrade" -eq 0 ] || printf ', %d downgraded'   "$apt_status_downgrade"
-[ "$apt_status_replace"   -eq 0 ] || printf ', %d replaced'     "$apt_status_replace"
-[ "$apt_status_remove"    -eq 0 ] || printf ', %d removed'      "$apt_status_remove"
-printf '\n'
+	say "Downloading packages...";
 
-printf 'Need to get %s of archives.\n' "$(numfmt --to=iec $total_size)"
-printf 'After unpacking %s of additional disk space will be used.\n' "$apt_status_disk_size"
+	open $fh, "|-", "curl", "-#", "--parallel-immediate", "--parallel-max", "$parallel", "-Z", "-K", "-" or
+		die "Can't start curl: $!";
 
-if [ -n "$confirm" ]; then
-	read -p 'Do you want to continue? [Y/n] ' ans
-	ans="${ans:-y}"
+	foreach my $missing (@{$info{'missing-files'}}) {
+		$missing->{url} =~ s/^copy:/file:/;
 
-	if [ "${ans,,}" != "y" ]; then
-		printf 'Abort.\n'
-		exit
-	fi
-fi
+		say $fh "url = $missing->{url}";
+		say $fh "output = $apt_dir_downloads/$missing->{filename}";
+	}
+	close $fh;
 
-if [ -s "$workdir/uris" ]; then
-	set_cleanup_handler exit_handler
+	say "Check the checksums...";
 
-	printf 'Downloading packages...\n'
+	foreach my $missing (@{$info{'missing-files'}}) {
+		my $algo = "MD5";
 
-	curl -# \
-		-Z --parallel-max "$parallel" --parallel-immediate \
-		-K "$workdir/uris"
+		SWITCH: {
+			$_ = $missing->{hash};
 
-	printf 'Check the checksums...\n'
+			if (/^(MD5|MD5SUM):/i) {
+				last SWITCH;
+			}
+			if (/^(SHA1|SHA256|SHA512):/i) {
+				$algo = uc($1);
+				last SWITCH;
+			}
+			if (/^([^:]+):.*/) {
+				die "Unknown checksum algorithm: $1";
+			}
+		}
 
-	for checksum in $(set +f && printf '%s ' "$workdir"/checksum.*); do
-		"${checksum##*.}sum" --quiet -c "$checksum"
+		my $digest_hex = digest_file_hex $algo, "$apt_dir_downloads/$missing->{filename}";
 
-		while read -r csum filename; do
-			mv $verbose -t "$apt_archives" -- "$filename"
-		done < "$checksum"
-	done
-fi
+		die "$missing->{filename}: expected checksum \`$missing->{hash}', but got \`$digest_hex'"
+			if $digest_hex ne $missing->{hash};
 
-printf 'Applying changes...\n'
+		rename "$apt_dir_downloads/$missing->{filename}", "$apt_dir_archives/$missing->{filename}" or
+			die "Unable to move package from downloads directory: $!";
+	}
+}
 
-set -o pipefail
-apt-get "$operation" "${apt_args[@]}" -y "$@" |
-	sed -n -e '/^Committing changes\.\.\./,$p'
+say "Applying changes...";
+
+if (open PTMX, '+<', '/dev/ptmx') {
+	my $tmp = '';
+	ioctl PTMX, &TIOCGPTN, $tmp or die "ioctl(TIOCGPTN): $!";
+
+	my $pts = unpack 'i', $tmp;
+
+	say "Using /dev/pts/$pts\n" if $verbose;
+
+	# unlockpt
+	my $unlock = pack 'i', 0;
+	ioctl PTMX, &TIOCSPTLCK, $unlock or die "ioctl(TIOCSPTLCK): $!";
+
+	my $pid = fork;
+	die "Unable to fork: $!" unless defined $pid;
+
+	if (!$pid) {
+		open STDIN,  "+<", "/dev/pts/$pts" or die "Unable to re-open stdin to /dev/pts/$pts: $!";
+
+		if (length $winsize > 0) {
+			ioctl STDIN, &TIOCSWINSZ, $winsize or die "ioctl(TIOCSWINSZ): $!";
+		}
+
+		open STDOUT, '>&', STDIN  or die "can't dup stdin: $!" ;
+		open STDERR, ">&", STDOUT or die "can't dup stdout: $!";
+
+		exec "apt-get", $command, "-y", "-o", "simple-output=yes", @ARGV or
+			die "Unable to exec apt-get";
+	}
+
+	my $rin = '';
+	vec($rin, fileno(PTMX), 1) = 1;
+
+	die "select: $!" if select(my $rout = $rin, undef, undef, undef) == -1;
+
+	while (<PTMX>) {
+		next if /^apt-get:/;
+		print;
+	}
+
+	close PTMX;
+	wait;
+	exit $?;
+}
+
+exec "apt-get", $command, "-y", "-o", "simple-output=yes", @ARGV or
+	die "Unable to exec apt-get";
